### ISSUE TITLE
Error encountered while training in Deep Network

### ISSUE THREAD

**Issue by StarryFire** [akshaybahadur21/Digit-Recognizer#1]
`/home/kartik/Desktop/Digit-Recognizer-master/Digit-Recognizer/Digit_Recognizer_DL.py:201:RuntimeWarning: divide by zero encountered in true_divide
  dA_last = - (np.divide(Y, A_last) - np.divide(1 - Y, 1 - A_last))

/home/kartik/Desktop/Digit-Recognizer-master/Digit-Recognizer/Digit_Recognizer_DL.py:201: RuntimeWarning: invalid value encountered in true_divide
  dA_last = - (np.divide(Y, A_last) - np.divide(1 - Y, 1 - A_last))

/home/kartik/Desktop/Digit-Recognizer-master/Digit-Recognizer/Digit_Recognizer_DL.py:33: RuntimeWarning: invalid value encountered in multiply
  dZ = dA * s * (1 - s)

/home/kartik/Desktop/Digit-Recognizer-master/Digit-Recognizer/Digit_Recognizer_DL.py:46: RuntimeWarning: invalid value encountered in less_equal
  dZ[Z <= 0] = 0`

**Comment by akshaybahadur21** [comment]
@StarryFire - I think 1-A_last is 0 and divide by zero would throw an error.
Put a conditional check to divide if 1-A_last != 0
